### ISSUE TITLE
Allow token refresh for apps accepting only Microsoft Accounts

### ISSUE THREAD

**Issue by DeboMac** [oxalica/onedrive-api#3]
If you want to use the crate on an App that has only Microsoft Account users enabled, the login_with_refresh_function fails with

`Application [xxxx] is configured for use by Microsoft Account users only. Please use the /consumers endpoint to serve this request.`

But if you just change the endpoint from [https://login.microsoftonline.com/common/oauth2/v2.0/token](https://login.microsoftonline.com/common/oauth2/v2.0/token) to [https://login.live.com/oauth20_token.srf](https://login.live.com/oauth20_token.srf), it works. 

The reference for this endpoint is on this page of the documentation: [https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online)

It would be great to have a way (in the Auth struct, or an argument in the function) of choosing the endpoint on which we want to make the request.

**Comment by oxalica** [comment]
From the documentation you pasted:
> However, this approach is no longer recommended. New applications should be developed using Microsoft Graph ...

It seems to be legacy authorization endpoint. I'm not sure if the token issued here is able to be used in Microsoft Graph API (which is used in all `OneDrive` methods).

**Comment by oxalica** [comment]
Okay, seems I misread the documentation. The new endpoint do have dedicated endpoints `https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize` where `tenant` is `consumers`. It's kinda weird that `common` API is not a "common" API but an API for account-agnostic applications. :thinking: 

https://learn.microsoft.com/en-us/graph/auth-v2-user?tabs=http#authorization-request
